export const JOB_CATEGORIES = [
  "Handyman",
  "Home Cleaning",
  "Deep Cleaning",
  "Move-in / Move-out Cleaning",
  "Plumbing",
  "Electrical",
  "HVAC / AC Repair",
  "Appliance Repair",
  "Painting (Interior)",
  "Painting (Exterior)",
  "Drywall / Sheetrock",
  "Carpentry",
  "Flooring (Tile)",
  "Flooring (Hardwood)",
  "Flooring (Vinyl / Laminate)",
  "Roofing",
  "Gutters",
  "Pressure Washing",
  "Landscaping",
  "Lawn Care",
  "Tree Service",
  "Pest Control",
  "Junk Removal",
  "Moving Services",
  "Furniture Assembly",
  "TV Mounting",
  "Home Security / Cameras",
  "Smart Home / Doorbell",
  "Garage Door",
  "Fence Repair",
  "Deck / Patio",
  "Concrete",
  "Windows / Doors",
  "Water Damage / Dry-out",
  "Pool Repair",
  "CNA / Home Care",
  "Elder Care",
  "Child Care",
  "Car Detailing",
  "Other",
] as const;
