// lib/jobCategoriesList.ts
export const JOB_CATEGORIES: string[] = [
  "Handyman / General Repairs",
  "Furniture Assembly",
  "TV Mounting",
  "Home Cleaning",
  "Deep Cleaning",
  "Move-In / Move-Out Cleaning",
  "Carpet Cleaning",
  "Pressure Washing",
  "Window Cleaning",
  "Gutter Cleaning",
  "Yard Work / Lawn Care",
  "Landscaping",
  "Tree Trimming",
  "Junk Removal",
  "Hauling / Delivery",
  "Moving Help",
  "Painting (Interior)",
  "Painting (Exterior)",
  "Drywall Repair",
  "Flooring / Tile",
  "Kitchen Remodel",
  "Bathroom Remodel",
  "Plumbing",
  "Toilet Repair / Install",
  "Faucet Repair / Install",
  "Water Heater Help",
  "Electrical",
  "Light Fixture Install",
  "Ceiling Fan Install",
  "Outlet / Switch Repair",
  "Smart Home Install",
  "Security Cameras Install",
  "Doorbell Camera Install",
  "Lock Change / Rekey",
  "Door Repair",
  "Window Repair",
  "Roof Repair",
  "Siding Repair",
  "HVAC / Heating & Air",
  "Appliance Repair",
  "Washer / Dryer Help",
  "Refrigerator Help",
  "Garage Door Repair",
  "Fence Repair / Install",
  "Deck / Porch Repair",
  "Concrete / Masonry",
  "Pest Control",
  "Pet Care",
  "Child Care / Babysitting",
  "Senior Care / Companion Care",
  "CNA / Home Health Aide",
  "Errands / Personal Assistant",
  "Tutoring",
  "IT Help / Tech Support",
  "Auto Detailing",
];
